const questions = [
"A. P. J. Abdul Kalam",
"Adele",
"Akbar",
"Akshay Kumar",
"Alia Bhatt",
"Amitabh Bachchan",
"Amy Winehouse",
"Anas Siddiqui",
"Angelina Jolie",
"Anushka Sharma",
"Ariana Grande",
"Barack Obama",
"Bhagat Singh",
"Bill Gates",
"Brad Pitt",
"Cristiano Ronaldo",
"Deepika Padukone",
"Disha Patani",
"Donald Trump",
"Dwayne The Rock Johnson",
"Ed Sheeran",
"Elon Musk",
"Emma Watson",
"Greta Thunberg",
"Hardik Pandya",
"Hrithik Roshan",
"Indira Gandhi",
"Jacqueline Fernandez",
"Jawaharlal Nehru",
"Jeff Bezos",
"Justin Bieber",
"Kapil Sharma",
"Kartik Aaryan",
"Katrina Kaif",
"Kiara Advani",
"Kim Kardashian",
"Kriti Sanon",
"Leonardo DiCaprio",
"Lionel Messi",
"Madhuri Dixit",
"Mahatma Gandhi",
"Mahendra Singh Dhoni",
"Mark Zuckerberg",
"Michael Jackson",
"Mother Teresa",
"Narendra Modi",
"Neha Kakkar",
"Nora Fatehi",
"Parineeti Chopra",
"Princess Diana",
"Priyanka Chopra",
"Ranveer Singh",
"Rihanna",
"Roger Federer",
"Rohit Sharma",
"Sachin Tendulkar",
"Salman Khan",
"Sara Ali Khan",
"Selena Gomez",
"Serena Williams",
"Shah Rukh Khan",
"Shahid Kapoor",
"Shakira",
"Shilpa Shetty",
"Shraddha Kapoor",
"Sidharth Malhotra",
"Sonam Kapoor",
"Stephen Hawking",
"Taylor Swift",
"Tiger Shroff",
"Tiger Woods",
"Tom Cruise",
"Urvashi Rautela",
"Varun Dhawan",
"Virat Kohli",
"Vladimir Putin",
"Will Smith",
"Zoheb Siddiqui",
];

export default questions;